### PR TITLE
reformat + update AS

### PR DESCRIPTION
**Pull request by MaxGraey**
- use faster and AS specific `NativeMath.sincos` which calc sin and cos at the same time for same angle.
- use [sorting networks](https://en.wikipedia.org/wiki/Sorting_network) for sort 4 elements.
- move `@assemblyscript/loader` to dependencies

All this improvements shave `~1 Kb`

### CODE REVIEW

**Comment by LeXXik** [comment]
Ooomph! This is amazing, very much appreciated, Max!

Speaking of size, I gave it a bit more consideration moving towards the exported globals vs arrays. One reason I use the assemblyscript's loader is to simplify the process of working with WASM arrays from Javascript side. However, if I would remove the need in Javascript to access the arrays, then there would be no need in using the loader, which can probably reduce the size even further, and potentially improving the performance as well along the way.  What do you think?

**Comment by MaxGraey** [comment]
Yes, if you eliminate pass parameters via arrays, loader will be unnecessary and you simplify your host and AS code significantly

**Comment by MaxGraey** [comment]
So in this PR I prepared code for refactoring to interop with imported / exported global variables instead of arrays. And I hope it will be much easier for you make this refactoring afterwards

**Comment by LeXXik** [comment]
Yes, it very much will be :) Thank you again, Max!

**Pull request merged**
