### PR TITLE
Speedup & improvements

### PR DESCRIPTION
**Pull request by MaxGraey**
Nice project!

Let me suggest some improvements which could slightly speed-up you calculations

### CODE REVIEW

**Comment by MaxGraey** [comment]
Also it seems you don't need pass buffers with parameters between js and wasm which quite expensive. Instead you could use finite count of exported / imported mutable globals (20 or less)

**Comment by MaxGraey** [comment]
Also found one porting (typo) error [here](https://github.com/LeXXik/ballistics/blob/master/assembly/index.ts#L501)

It should be `let i = 0; i < numTimes && numSolutions < 2; ++i` according to [original](https://github.com/forrestthewoods/lib_fts/blob/master/code/fts_ballistic_trajectory.cs#L411). But when change this line one of the test failed.

**Comment by LeXXik** [comment]
Thank you for looking into it, @MaxGraey !

Those look fine to me. A question I may have is the choice of `-O3s` over `-O3z`. If I understood correctly, the `s` one focuses on library size, while `z` on performance. I remember I tried `s`, but saw no noticeable changes in the final size. As a result, I used `z` in the hopes a compiler may squeeze out a tiny bit performance optimization.

I need to look into `numTimes`. Must be a bug, good catch.

**Comment by LeXXik** [comment]
About the mutable globals, I like the idea. I started with arrays, because it was easy to work with them. Is 20 you mentioned a hard limit on exported globals? Not that I would need more for this library, though.

**Comment by MaxGraey** [comment]
> If I understood correctly, the s one focuses on library size, while z on performance

No, postfix `s` means `shrinkLevel = 1` and `z` means `shrinkLevel = 2`. Both are focused on sizes. If you want maximum speed I recommend use `-O3` without any postfixes. AS pretty sensitive to this flags due to we use different strategies and even algorithms for size / speed trade-offs.

**Comment by MaxGraey** [comment]
> About the mutable globals, I like the idea. I started with arrays, because it was easy to work with them. Is 20 you mentioned a hard limit on exported globals? Not that I would need more for this library, though.

`20` is just number which currently using. I guess it will less number of usage so fit number to actual used variables

**Pull request merged**
